"""Research Agent implementation and its supporting contracts."""

from agent.research.agent import (
    DuplicateHypothesisError,
    LLMResearchAgent,
    ResearchAgentError,
    ResearchInputError,
    ResearchOutputError,
    ResearchUsageLog,
)

from agent.research.citations import (
    CitationClaim,
    CitationRecord,
    CitationSource,
    CitationValidationError,
    CompositeCitationSource,
    JsonCitationCatalog,
    ResolvedCitation,
    validate_proposal_citations,
)
from agent.research.context import (
    IncumbentSummary,
    IterationSummary,
    ResearchContext,
    build_history_fingerprint,
    build_research_context,
)
from agent.research.offline import (
    DEFAULT_BACKLOG,
    BacklogEntry,
    OfflineBacklogExhausted,
    OfflineResearchAgent,
    OfflineResearchError,
)
from agent.research.retrieval import (
    DatasetProfile,
    DatasetSignal,
    QueryPlan,
    QueryPlanner,
    GapStatus,
    InertEvidenceText,
    ResearchIntent,
    ResearchMemory,
    ResearchQuery,
    ResearchSafetyError,
    ResearchSafetyScanner,
    SafetyRejectionReason,
    StaleResearchMemoryError,
    RetrievalBudget,
    RetrievalValidationError,
    build_context_fingerprint,
    deterministic_fingerprint,
    load_dataset_profile,
)
from agent.research.schemas import (
    EvaluationPlan,
    EvidenceReference,
    FeasibilityAssessment,
    ImplementationPlan,
    ProposalValidationError,
    Rationale,
    ResearchProposal,
)

__all__ = [
    "CitationClaim",
    "CitationRecord",
    "CitationSource",
    "CitationValidationError",
    "CompositeCitationSource",
    "DEFAULT_BACKLOG",
    "DatasetProfile",
    "DatasetSignal",
    "DuplicateHypothesisError",
    "EvaluationPlan",
    "GapStatus",
    "EvidenceReference",
    "FeasibilityAssessment",
    "ImplementationPlan",
    "IncumbentSummary",
    "InertEvidenceText",
    "IterationSummary",
    "JsonCitationCatalog",
    "LLMResearchAgent",
    "BacklogEntry",
    "OfflineBacklogExhausted",
    "OfflineResearchAgent",
    "OfflineResearchError",
    "ProposalValidationError",
    "QueryPlan",
    "QueryPlanner",
    "Rationale",
    "ResearchAgentError",
    "ResearchContext",
    "ResearchIntent",
    "ResearchInputError",
    "ResearchMemory",
    "ResearchOutputError",
    "ResearchProposal",
    "ResearchQuery",
    "ResearchSafetyError",
    "ResearchSafetyScanner",
    "SafetyRejectionReason",
    "StaleResearchMemoryError",
    "ResearchUsageLog",
    "RetrievalBudget",
    "RetrievalValidationError",
    "ResolvedCitation",
    "build_context_fingerprint",
    "build_history_fingerprint",
    "build_research_context",
    "deterministic_fingerprint",
    "load_dataset_profile",
    "validate_proposal_citations",
]
